name: flutter_login_register_ui
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The version and build number of the app
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Main dependencies
dependencies:
  flutter:
    sdk: flutter
    # flutter_svg: ^1.1.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

# Flutter specific packages
flutter:

  uses-material-design: true

  # Add project assets
  assets:
    - assets/images/
    - assets/fonts/
